name: Umusa Daily File Uploader

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4-18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UMUSA_SECRET: ${{ secrets.UMUSA_SECRET }}
      SERVICEM8_SECRET: ${{ secrets.SERVICEM8_SECRET }}
      UMUSA_AZURE: ${{ secrets.UMUSA_AZURE }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          # cache: 'pip'

      - name: Install dependencies
        run: pip install -r config/requirements.txt

      - name: File Uploader
        run: python file_uploader/file_uploader.py
        continue-on-error: true

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update last_run.json" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
