name: Secret Print

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Print Secret
      env:
        UMUSA_AZURE: ${{ secrets.UMUSA_AZURE }}
      run: python -c "import os, json; print(json.loads(os.environ.get('UMUSA_AZURE')))"
